inclusion:
  files: []
  directories:
  - C:\Users\sharatdev\Desktop\projects\Intelligent-Document-Reference-Winter2026\datasets\dataset8
exclusion:
  files: []
  directories: []
  patterns: []
context:
  files: []
