inclusion:
  files:
  - C:\Users\sharatdev\Downloads\report (2).pdf
  - C:\Users\sharatdev\Downloads\math.pdf
  directories: []
exclusion:
  files: []
  directories: []
  patterns: []
context:
  files:
  - C:\Users\sharatdev\Downloads\report (2).pdf
  - C:\Users\sharatdev\Downloads\math.pdf
